### ISSUE TITLE
bump nixpkgs

### ISSUE THREAD

**Issue by NotAShelf** [NotAShelf/neovim-flake#146]
We are currently running a little behind on nixpkgs, which causes recent changes #144 to break on systems that do not override nixpkgs inputs from thix flake.

The nixpkgs bump, however, is blocked by an error in [nmd](https://git.sr.ht/~rycee/nmd)

```bash
last 4 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/0damjdjmnbf31gh3y6hvgz2v9nranaaw-docbookify-options-json.py", line 72, in <module>
       >     class Renderer(mistune.renderers.BaseRenderer):
       > AttributeError: module 'mistune.renderers' has no attribute 'BaseRenderer'
```

caused by https://github.com/NixOS/nixpkgs/pull/245838 which bumped mistune from 2.0.5 to 3.0.1

We will need to either fork nmd to fix the docbookify-options-json scriptü or find a way to override mistune locally for nmd
