### ISSUE TITLE
bump nixpkgs

### ISSUE THREAD

**Issue by NotAShelf** [NotAShelf/neovim-flake#147]
We are currently running a little behind on nixpkgs, which causes recent changes #144 to break on systems that do not override nixpkgs inputs from this flake.

The nixpkgs bump, however, is blocked by an error in [nmd](https://git.sr.ht/~rycee/nmd)

```bash
last 4 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/0damjdjmnbf31gh3y6hvgz2v9nranaaw-docbookify-options-json.py", line 72, in <module>
       >     class Renderer(mistune.renderers.BaseRenderer):
       > AttributeError: module 'mistune.renderers' has no attribute 'BaseRenderer'
```

caused by https://github.com/NixOS/nixpkgs/pull/245838 which bumped mistune from 2.0.5 to 3.0.1

We will need to either fork nmd to fix the docbookify-options-json script or find a way to override `mistune` locally for nmd

CC @horriblename

**Comment by NotAShelf** [comment]
I've tried overriding nmd's own packages in docs/default.nix - doesn't seem to help with the issue

**Comment by horriblename** [comment]
I briefly looked into migrating nmd to mistune 3.0.1, it looks doable, I think, I'll look into that. 

idk how we can override the package though. I can't figure out where python gets its packages from

**Comment by NotAShelf** [comment]
We'll probably need to write an overlay - which I *really* want to avoid but may be our only choice
I'll try using an overlay tomorrow, if it doesn't work we can try updating to mistune 3.0.1

**Comment by NotAShelf** [comment]
unfortunately overlays don't seem to help with the issue (not surprised) and the maintainer of nmd is completely radio silent on matrix. we'll probably need to look into forking nmd and update to mistune 3.0.1

**Comment by NotAShelf** [comment]
Closed by #148 and #149
